"""empty message

Revision ID: 06f7d4b66eee
Revises: 93ff45e09096
Create Date: 2022-01-27 14:40:58.308566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f7d4b66eee'
down_revision = '93ff45e09096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('skills_required', sa.String(length=2000), nullable=True))
    op.add_column('jobs', sa.Column('responsiblities', sa.String(length=2000), nullable=True))
    op.add_column('jobs', sa.Column('official_link', sa.String(length=200), nullable=False))
    op.add_column('jobs', sa.Column('end_data', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'end_data')
    op.drop_column('jobs', 'official_link')
    op.drop_column('jobs', 'responsiblities')
    op.drop_column('jobs', 'skills_required')
    # ### end Alembic commands ###
