"""empty message

Revision ID: 12927c19f586
Revises: 9bf76bd0fffa
Create Date: 2022-01-27 19:57:49.104242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12927c19f586'
down_revision = '9bf76bd0fffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('branch', sa.String(length=100), nullable=False))
    op.drop_column('jobs', 'joblink')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('joblink', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('jobs', 'branch')
    # ### end Alembic commands ###
