"""empty message

Revision ID: 63db68b5aa42
Revises: 20d6b579456d
Create Date: 2022-02-02 12:40:23.748495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63db68b5aa42'
down_revision = '20d6b579456d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Problemsolving',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('posted_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('codingproblems')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codingproblems',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('question', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('expl_input', mysql.TEXT(), nullable=False),
    sa.Column('expl_output', mysql.TEXT(), nullable=False),
    sa.Column('solution', mysql.TEXT(), nullable=False),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Problemsolving')
    # ### end Alembic commands ###
