"""empty message

Revision ID: 8a1457af7b24
Revises: 06f7d4b66eee
Create Date: 2022-01-27 14:46:26.703470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a1457af7b24'
down_revision = '06f7d4b66eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.drop_column('jobs', 'end_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('end_data', mysql.DATETIME(), nullable=True))
    op.drop_column('jobs', 'end_date')
    # ### end Alembic commands ###
