"""empty message

Revision ID: ab8162bcbc6a
Revises: 63db68b5aa42
Create Date: 2022-02-05 05:34:37.813309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab8162bcbc6a'
down_revision = '63db68b5aa42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Problemsolving',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ques_topic', sa.String(length=100), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('posted_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('problemsolving')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problemsolving',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', mysql.TEXT(), nullable=False),
    sa.Column('input', mysql.TEXT(), nullable=False),
    sa.Column('output', mysql.TEXT(), nullable=False),
    sa.Column('explanation', mysql.TEXT(), nullable=False),
    sa.Column('code', mysql.TEXT(), nullable=False),
    sa.Column('posted_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Problemsolving')
    # ### end Alembic commands ###
